// TODO: don't hardcode these. They should be parameterized
// according to the options set in Kbuild
#define NAUT_CONFIG_MAX_CPUS 1
#define NAUT_CONFIG_MAX_THREADS 1
#define NAUT_CONFIG_MAX_IOAPICS 1
#define NAUT_CONFIG_X86_64_HOST
#define __NAUTILUS__

// TODO: perhaps rename the `main` function in
// `include/arch/x64/main.h` because (annoyingly)
// clang treats a wrongly-typed `main` as a hard error
// (ie. forcing the signature to be `int main(int x, char** y)`)
#define BINDGEN_ELIDE_MAIN

#include "config/debug/numa.h"
#include "config/debug/barrier.h"
#include "config/debug/filesystem.h"
#include "config/debug/gpudev.h"
#include "config/debug/apic.h"
#include "config/debug/loader.h"
#include "config/debug/netdev.h"
#include "config/debug/sched.h"
#include "config/debug/pci.h"
#include "config/debug/chardev.h"
#include "config/debug/semaphores.h"
#include "config/debug/smp.h"
#include "config/debug/pit.h"
#include "config/debug/blkdev.h"
#include "config/debug/linker.h"
#include "config/debug/cxx.h"
#include "config/debug/rust.h"
#include "config/debug/info.h"
#include "config/debug/remote/debugger.h"
#include "config/debug/synch.h"
#include "config/debug/kmem.h"
#include "config/debug/dev.h"
#include "config/debug/paging.h"
#include "config/debug/sfi.h"
#include "config/debug/fpu.h"
#include "config/debug/buddy.h"
#include "config/debug/ioapic.h"
#include "config/debug/tests.h"
#include "config/debug/msg/queues.h"
#include "config/debug/timers.h"
#include "config/debug/bootmem.h"
#include "config/debug/cmdline.h"
#include "config/debug/prints.h"
#include "config/debug/waitqueues.h"
#include "config/debug/tasks.h"
#include "config/debug/futures.h"
#include "config/debug/shell.h"
#include "config/debug/virtual/console.h"
#include "config/debug/ps2.h"
#include "config/debug/group/barrier.h"
#include "config/debug/group/sched.h"
#include "config/debug/pmc.h"
#include "config/debug/threads.h"
#include "config/debug/group.h"
#include "nautilus/acpi.h"
#include "nautilus/acpi-x86_64.h"
#include "nautilus/aspace.h"
#include "nautilus/atomic.h"
#include "nautilus/backtrace.h"
#include "nautilus/barrier.h"
#include "nautilus/bits.h"
#include "nautilus/blkdev.h"
#include "nautilus/buddy.h"
#include "nautilus/bug.h"
#include "nautilus/cachepart.h"
#include "nautilus/chardev.h"
#include "nautilus/cmdline.h"
#include "nautilus/condvar.h"
#include "nautilus/cpu.h"
#include "nautilus/cpuid.h"
#include "nautilus/cpu_state.h"
#include "nautilus/cxxglue.h"
#include "nautilus/dev.h"
#include "nautilus/doprnt.h"
#include "nautilus/dr.h"
#include "nautilus/elf-em.h"
#include "nautilus/elf.h"
#include "nautilus/errno.h"
#include "nautilus/fiber.h"
#include "nautilus/fmtout.h"
#include "nautilus/fprintk.h"
#include "nautilus/fpu.h"
#include "nautilus/fs.h"
#include "nautilus/future.h"
#include "nautilus/gdb-stub.h"
#include "nautilus/gdt.h"
#include "nautilus/getopt.h"
#include "nautilus/gpudev.h"
#include "nautilus/group.h"
#include "nautilus/group_sched.h"
#include "nautilus/hashtable.h"
#include "nautilus/idle.h"
#include "nautilus/idt.h"
#include "nautilus/instrument.h"
#include "nautilus/intrinsics.h"
#include "nautilus/irq.h"
#include "nautilus/isocore.h"
#include "nautilus/libccompat.h"
#include "nautilus/limits.h"
// TODO: issue with redefinition of `struct symentry`
// #include "nautilus/linker.h"
#include "nautilus/list.h"
#include "nautilus/loader.h"
#include "nautilus/macros.h"
#include "nautilus/math.h"
#include "nautilus/mb_utils.h"
#include "nautilus/mcslock.h"
#include "nautilus/mm.h"
#include "nautilus/module.h"
#include "nautilus/monitor.h"
#include "nautilus/msg_queue.h"
#include "nautilus/msr.h"
#include "nautilus/mtrr.h"
#include "nautilus/multiboot2.h"
#include "nautilus/mwait.h"
#include "nautilus/naut_assert.h"
#include "nautilus/nautilus_exe.h"
#include "nautilus/nautilus.h"
#include "nautilus/naut_string.h"
#include "nautilus/naut_types.h"
#include "nautilus/nemo.h"
#include "nautilus/netdev.h"
#include "nautilus/numa.h"
#include "nautilus/paging.h"
#include "nautilus/partition.h"
#include "nautilus/percpu.h"
#include "nautilus/pmc.h"
#include "nautilus/printk.h"
#include "nautilus/prog.h"
#include "nautilus/provenance.h"
#include "nautilus/queue.h"
#include "nautilus/random.h"
#include "nautilus/rbtree.h"
// TODO: issue with packed+aligned struct `nk_real_mode_int_args`
// #include "nautilus/realmode.h"
#include "nautilus/rwlock.h"
#include "nautilus/scheduler.h"
#include "nautilus/semaphore.h"
#include "nautilus/setjmp.h"
#include "nautilus/sfi.h"
#include "nautilus/shell.h"
#include "nautilus/shutdown.h"
#include "nautilus/smp.h"
#include "nautilus/spinlock.h"
#include "nautilus/task.h"
#include "nautilus/testfs.h"
#include "nautilus/thread.h"
#include "nautilus/ticketlock.h"
#include "nautilus/timer.h"
#include "nautilus/topo.h"
#include "nautilus/vc.h"
#include "nautilus/vmm.h"
#include "nautilus/waitqueue.h"
#include "nautilus/watchdog.h"
